# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
                ('hall_price', models.IntegerField()),
                ('hall_rows', models.IntegerField()),
                ('hall_cols', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('session_time', models.TimeField()),
                ('film_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Film')),
                ('hall_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_row', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
                ('ticket_col', models.IntegerField()),
                ('ticket_sold', models.BooleanField(default=False)),
                ('ticket_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Session')),
            ],
        ),
    ]
